// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDocSetIndex(arg1, arg2) {
  return window['go']['search']['Search']['CreateDocSetIndex'](arg1, arg2);
}

export function SearchDocSet(arg1, arg2) {
  return window['go']['search']['Search']['SearchDocSet'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['search']['Search']['Startup'](arg1);
}
