// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseIndex(arg1) {
  return window['go']['indexer']['Indexer']['CloseIndex'](arg1);
}

export function CreateDocSetIndex(arg1, arg2) {
  return window['go']['indexer']['Indexer']['CreateDocSetIndex'](arg1, arg2);
}

export function SearchDocSet(arg1, arg2) {
  return window['go']['indexer']['Indexer']['SearchDocSet'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['indexer']['Indexer']['Startup'](arg1);
}
