// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {context} from '../models';

export function LoadSettings(arg1:string):Promise<config.LoadSettingsResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function WriteSettings(arg1:string,arg2:config.ConfigObject):Promise<string>;
