// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings(arg1) {
  return window['go']['config']['Config']['LoadSettings'](arg1);
}

export function Startup(arg1) {
  return window['go']['config']['Config']['Startup'](arg1);
}

export function WriteSettings(arg1, arg2) {
  return window['go']['config']['Config']['WriteSettings'](arg1, arg2);
}
