// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DecompressDocSetArchive(arg1, arg2) {
  return window['go']['docsets']['DocSets']['DecompressDocSetArchive'](arg1, arg2);
}

export function DownloadFeedArchive(arg1, arg2, arg3) {
  return window['go']['docsets']['DocSets']['DownloadFeedArchive'](arg1, arg2, arg3);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['docsets']['DocSets']['DownloadFile'](arg1, arg2, arg3);
}

export function GetDownloadedDocSetPaths(arg1) {
  return window['go']['docsets']['DocSets']['GetDownloadedDocSetPaths'](arg1);
}

export function ReadFeedArchive(arg1) {
  return window['go']['docsets']['DocSets']['ReadFeedArchive'](arg1);
}

export function Startup(arg1) {
  return window['go']['docsets']['DocSets']['Startup'](arg1);
}
