// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {docsets} from '../models';
import {context} from '../models';

export function DecompressDocSetArchive(arg1:string,arg2:string):Promise<string>;

export function DownloadFeedArchive(arg1:string,arg2:string,arg3:string):Promise<string>;

export function DownloadFile(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GetDownloadedDocSetPaths(arg1:string):Promise<docsets.GetDownloadedDocSetPaths>;

export function ReadFeedArchive(arg1:string):Promise<docsets.ReadFeedArchiveResult>;

export function Startup(arg1:context.Context):Promise<void>;
