// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {context} from '../models';

export function Close(arg1:string):Promise<void>;

export function CreateFuzzySearchIndex(arg1:string):Promise<string>;

export function ImportSearchIndex(arg1:string,arg2:string):Promise<string>;

export function OpenDB(arg1:string):Promise<string>;

export function SearchDocSet(arg1:string,arg2:string):Promise<db.SearchDocSetResult>;

export function Startup(arg1:context.Context):Promise<void>;

export function TableExists(arg1:string,arg2:string):Promise<boolean>;
