// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {fs} from '../models';
import {context} from '../models';

export function CreateDir(arg1:string):Promise<void>;

export function DoesPathExist(arg1:string):Promise<boolean>;

export function GetPathSeperator():Promise<string>;

export function ReadDir(arg1:string):Promise<Array<fs.DirEntry>>;

export function ReadTextFile(arg1:string):Promise<string>;

export function RemoveDir(arg1:string):Promise<void>;

export function RemoveFile(arg1:string):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
