// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDir(arg1) {
  return window['go']['fs']['FS']['CreateDir'](arg1);
}

export function DoesPathExist(arg1) {
  return window['go']['fs']['FS']['DoesPathExist'](arg1);
}

export function GetPathSeperator() {
  return window['go']['fs']['FS']['GetPathSeperator']();
}

export function ReadDir(arg1) {
  return window['go']['fs']['FS']['ReadDir'](arg1);
}

export function ReadTextFile(arg1) {
  return window['go']['fs']['FS']['ReadTextFile'](arg1);
}

export function RemoveDir(arg1) {
  return window['go']['fs']['FS']['RemoveDir'](arg1);
}

export function RemoveFile(arg1) {
  return window['go']['fs']['FS']['RemoveFile'](arg1);
}

export function Startup(arg1) {
  return window['go']['fs']['FS']['Startup'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['fs']['FS']['WriteFile'](arg1, arg2);
}
