// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName() {
  return window['go']['main']['App']['GetAppName']();
}

export function GetUserConfigDir() {
  return window['go']['main']['App']['GetUserConfigDir']();
}

export function GetUserDataDir() {
  return window['go']['main']['App']['GetUserDataDir']();
}
