// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAppName():Promise<string>;

export function GetUserConfigDir():Promise<string>;

export function GetUserDataDir():Promise<string>;
